---
version: '3'
services:
  netbox:
    build:
      context: ../
      dockerfile: develop/Dockerfile
    command: sh -c "./manage.py migrate && ./manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    depends_on:
      - postgres
      - redis
    env_file:
      - ./dev.env
    volumes:
      - ./configuration.py:/opt/netbox/netbox/netbox/configuration.py
      - ../netbox_vlan_manager:/opt/plugin/netbox_vlan_manager
  worker:
    build:
      context: ../
      dockerfile: develop/Dockerfile
    command: sh -c "./manage.py rqworker"
    depends_on:
      - netbox
    env_file:
      - ./dev.env
    volumes:
      - ./configuration.py:/opt/netbox/netbox/netbox/configuration.py
      - ../netbox_vlan_manager:/opt/plugin/netbox_vlan_manager
  postgres:
    image: postgres:12
    env_file: dev.env
    volumes:
      - pgdata_netbox_vlan_group_manager:/var/lib/postgresql/data
  redis:
    image: redis:5
    command: sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    env_file: ./dev.env
volumes:
  pgdata_netbox_vlan_group_manager:
